# -----------------------------------------------------
# Monitor Setup: Upper 34" Ultrawide + Lower 27" 4K (Centered)
# name: "Dual Vertical (34" Top + 27" Bottom)"
# -----------------------------------------------------

monitor = desc:CMT GM34-CWQ2 CMI235200056, 3440x1440@100.0, 0x0, 1.0, vrr, 0
monitor = desc:Dell Inc. DELL U2723QE 4ZJP4P3, 3840x2160@60.0, 440x1440, 1.5, vrr, 0
